discord_apikey: ush9Zohzie6ahmohsoo6meCh.IThah7.jeephaijiachu8kuWoh0aephe5e
bitly_token: 705b20a9d090e616bb16e577282c3d1a474da61a
quote: ";"
pingpong: true
dictionaries:
    - name: sample

      # http or fs
      filesrc: fs
      path: /sample.csv

      # apply for http (set dummy valid value if using fs)
      timeout: 3

      # discord-smart [default]
      # custom-smart
      #   - if not starts_with http
      # never
      concat_url_prefix: discord-smart
      custom_url_prefix: https://example.com/images/

      # custom-smart
      #   - if not starts_with http
      # never [default]
      concat_url_suffix: never
      custom_url_suffix: ?size=1024

      # always
      # without-video [default]
      #   - if not ends_with mp4, gif
      # never
      use_bitly: without-video

      # mention protection (replace '@' to '%40')
      mention_protection: true

      # auto reload (0: disabled)
      interval_reload_sec: 0

      # reload on message
      reload_on_message: true

      # limit (global)
      reload_limit_sec: 0

      # whitelist or blacklist
      guild_selection_mode: blacklist
      guilds:

    - name: main

      # http or fs
      filesrc: http
      path: https://docs.google.com/spreadsheets/dPeo1aekaeRieporah8JaewahZoo7peyaiTohbout3akaH/export?format=csv

      # apply for http (set dummy valid value if using fs)
      timeout: 3

      # discord-smart [default]
      # custom-smart
      #   - if not starts_with http
      # never
      concat_url_prefix: discord-smart
      custom_url_prefix: https://example.com/images/

      # custom-smart
      #   - if not starts_with http
      # never [default]
      concat_url_suffix: never
      custom_url_suffix: ?size=1024

      # always
      # without-video [default]
      #   - if not ends_with mp4, gif
      # never
      use_bitly: without-video

      # mention protection (replace '@' to '%40')
      mention_protection: true

      # auto reload (0: disabled)
      interval_reload_sec: 0

      # reload on message
      reload_on_message: true

      # limit (global)
      reload_limit_sec: 30

      # whitelist or blacklist
      guild_selection_mode: whitelist
      guilds:
          - 538835926210823966
          - 316697955710281710

